const mountainsData = [
  {
    name: 'Greater Chimgan',
    latitude: 41.4951900,
    longitude: 70.0586718,
    elevation: 3309.6,
    image: 'mnt/mnt_01.svg',
    current_weather: {
      temperature: null,
      windspeed: null,
      windderection: null,
      time: null,
    },
  },
  {
    name: 'Karakush',
    latitude: 41.2477890,
    longitude: 70.3391467,
    elevation: 3864.3,
    image: 'mnt/mnt_02.svg',
    current_weather: {
      temperature: null,
      windspeed: null,
      windderection: null,
      time: null,
    },
  },
  {
    name: 'Babaitag',
    latitude: 41.1549650,
    longitude: 70.2232660,
    elevation: 3555.7,
    image: 'mnt/mnt_03.svg',
    current_weather: {
      temperature: null,
      windspeed: null,
      windderection: null,
      time: null,
    },
  },
  {
    name: 'Kizilbash',
    latitude: 42.0727687,
    longitude: 70.4667018,
    elevation: 4200,
    image: 'mnt/mnt_04.svg',
    current_weather: {
      temperature: null,
      windspeed: null,
      windderection: null,
      time: null,
    },
  },
  {
    name: 'Tavalgan',
    latitude: 41.7915524,
    longitude: 70.4090762,
    elevation: 3888.8,
    image: 'mnt/mnt_05.svg',
    current_weather: {
      temperature: null,
      windspeed: null,
      windderection: null,
      time: null,
    },
  },
  {
    name: 'Adelunga',
    latitude: 42.1235559,
    longitude: 70.9689168,
    elevation: 4301.8,
    image: 'mnt/mnt_06.svg',
    current_weather: {
      temperature: null,
      windspeed: null,
      windderection: null,
      time: null,
    },
  },
  {
    name: 'Xodja Gur Gur Ota',
    latitude: 38.3828229,
    longitude: 67.2788411,
    elevation: 3723.7,
    image: 'mnt/mnt_07.svg',
    current_weather: {
      temperature: null,
      windspeed: null,
      windderection: null,
      time: null,
    },
  },
  {
    name: 'Hazret Sultan',
    latitude: 38.9477782,
    longitude: 68.1724695,
    elevation: 4643,
    image: 'mnt/mnt_08.svg',
    current_weather: {
      temperature: null,
      windspeed: null,
      windderection: null,
      time: null,
    },
  },
];

export default mountainsData;
